------------------------------- 테이블 드랍
DROP TABLE RENTAL_CAR_BRANCH;
DROP TABLE RENTAL_CAR_BRANCHES_CAR;
DROP TABLE POINT;
DROP TABLE CONSULT;
DROP TABLE BOARD;
DROP TABLE IMAGE_FILE;
DROP TABLE RENTAL_CAR_RESERVATION;
DROP TABLE RENTAL_CAR;
DROP TABLE NEW_CAR;
DROP TABLE LICENSE;
DROP TABLE PAYMENT;
DROP TABLE MEMBER;
DROP TABLE COMMON_CODE;

------------------------------- 시퀀스 드랍
DROP SEQUENCE SEQ_POINT_NO;
DROP SEQUENCE SEQ_CONSULT_NO;
DROP SEQUENCE SEQ_BOARD_NO;
DROP SEQUENCE SEQ_IMAGE_FILE_NO;
DROP SEQUENCE SEQ_NEW_CAR_NO;
DROP SEQUENCE SEQ_LICENSE_NO;
DROP SEQUENCE SEQ_RESERVATION_NO;
DROP SEQUENCE SEQ_PAY_NO;

DROP VIEW RENTAL_CAR_VIEW;
DROP FUNCTION FN_COMM_NAME;
DROP FUNCTION FN_COMM_NM;
DROP FUNCTION FN_RES_NO;










