------------------------------- 테이블 드랍
DROP TABLE COMMON_CODE;
DROP TABLE MEMBER;
DROP TABLE RENTAL_CAR;
DROP TABLE RENTAL_CAR_BRANCH;
DROP TABLE RENTAL_CAR_BRANCHES_CAR;
DROP TABLE COUPON;
DROP TABLE MEMBER_COUPONS;
DROP TABLE POINT;
DROP TABLE CONSULT;
DROP TABLE BOARD;
DROP TABLE IMAGE_FILE;
DROP TABLE RENTAL_CAR_RESERVATION;
DROP TABLE NEW_CAR;

------------------------------- 시퀀스 드랍
DROP SEQUENCE SEQ_CAR_BRANCH_NO;
DROP SEQUENCE SEQ_POINT_NO;
DROP SEQUENCE SEQ_CONSULT_NO;
DROP SEQUENCE SEQ_BOARD_NO;
DROP SEQUENCE SEQ_IMAGE_FILE_NO;
DROP SEQUENCE SEQ_NEW_CAR_NO;












