INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '홍성혜', '010-0000-0000', 'HSH@geniecar.com', '영국 여행 가고 싶어요!', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '홍경영', '010-0000-0000', 'HKY@geniecar.com', '미국 여행 가고 싶어요!', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '이재진', '010-0000-0000', 'LJJ@geniecar.com', '우주 여행 가고 싶어요!', 'SEO001', SYSDATE, 'N');

COMMIT;