-- 이용후기는 시연 컴에 직접 입력
-- 이미지는 프로젝트 이미지 폴더 안에 geniecar_images 파일을 자기 컴 C:\geniecar_images 폴더에 복사할 것.

-- 공지사항 삽입
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '지니카 그랜드 오픈 안내', '공지사항 내용입니다.1', 0, 'NOTICE', 'N', NULL, 1, '2023/03/01', '2023/03/10', 'ADMIN', '2023-12-25', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '*업계최초* 국산 전차종 5시간 출고보장', '공지사항 내용입니다.2', 0, 'NOTICE', 'N', NULL, 2, '2023/03/01', '2023/03/10', 'ADMIN', '2023-12-25', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '시스템 개선을 위한 서버 점검 안내', '공지사항 내용입니다.3', 0, 'NOTICE', 'N', NULL, 3, '2023/03/01', '2023/03/10', 'ADMIN', '2024-01-02', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, 'EV6, GV70 추가 입고완료!!', '공지사항 내용입니다.4', 0, 'NOTICE', 'N', NULL, 4, '2023/03/01', '2023/03/10', 'ADMIN', '2024-01-05', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '지니카드 정기결제 등록오류 안내 1/10(수)~ 1/11(목)', '공지사항 내용입니다.5', 0, 'NOTICE', 'N', NULL, 5, '2023/03/01', '2023/03/10', 'ADMIN', '2024-01-09', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '★2024년 아이오닉5  입고 완료!★', '공지사항 내용입니다.6', 0, 'NOTICE', 'N', NULL, 6, '2023/03/01', '2023/03/10', 'ADMIN', '2024-01-16', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '물류서비스 지연안내 (요소수 품귀현상)', '공지사항 내용입니다.7', 0, 'NOTICE', 'N', NULL, 7, '2023/03/01', '2023/03/10', 'ADMIN', '2024-01-28', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '다이렉트 상담센터 상담 지연 안내', '공지사항 내용입니다.8', 0, 'NOTICE', 'N', NULL, 8, '2023/03/01', '2023/03/10', 'ADMIN', '2024-01-28', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '★2024년 신형 팰리세이드 입고 알림★', '공지사항 내용입니다.9', 0, 'NOTICE', 'N', NULL, 9, '2023/03/01', '2023/03/10', 'ADMIN', '2024-02-02', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '화물연대 파업에 따른 TP탁송 지연 안내', '공지사항 내용입니다.10', 0, 'NOTICE', 'N', NULL, 10, '2023/03/01', '2023/03/10', 'ADMIN', '2024-02-03', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '2월 프로모션 종료임박 및 신규차량 입고안내', '공지사항 내용입니다.11', 0, 'NOTICE', 'N', NULL, 11, '2023/03/01', '2023/03/10', 'ADMIN', '2024-02-06', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '2월 계약고객 전원 혜택', '공지사항 내용입니다.12', 0, 'NOTICE', 'N', NULL, 12, '2023/03/01', '2023/03/10', 'ADMIN', '2024-02-08', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '*지니카 역마진 프로모션 마감임박*', '공지사항 내용입니다.13', 0, 'NOTICE', 'N', NULL, 13, '2023/03/01', '2023/03/10', 'ADMIN', '2024-02-12', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '24년 2월 신차맞춤 차량별 예상 생산/출고 소요기간 안내해드립니다.', '공지사항 내용입니다.14', 0, 'NOTICE', 'N', NULL, 14, '2023/03/01', '2023/03/10', 'ADMIN', '2024-02-14', 'ADMIN', '2023/03/15');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '24년 2월 수탁사 변경에 따른 개인정보 처리방침 변경 공지', '공지사항 내용입니다.14', 0, 'NOTICE', 'N', NULL, 15, '2023/03/01', '2023/03/10', 'ADMIN', '2024-02-17', 'ADMIN', '2023/03/15');

-- 공지사항 이미지 삽입
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(1, 1, 'geniecar_image', 'notice1.png', 'notice1', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(2, 1, 'geniecar_image', 'notice2.png', 'notice2', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(3, 1, 'geniecar_image', 'notice3.png', 'notice3', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(4, 1, 'geniecar_image', 'notice4.png', 'notice4', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(5, 1, 'geniecar_image', 'notice5.png', 'notice5', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(6, 1, 'geniecar_image', 'notice6.png', 'notice6', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(7, 1, 'geniecar_image', 'notice7.png', 'notice7', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(8, 1, 'geniecar_image', 'notice8.png', 'notice8', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(9, 1, 'geniecar_image', 'notice9.png', 'notice9', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(10, 1, 'geniecar_image', 'notice10.png', 'notice10', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(11, 1, 'geniecar_image', 'notice11.png', 'notice11', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(12, 1, 'geniecar_image', 'notice12.png', 'notice12', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(13, 1, 'geniecar_image', 'notice13.png', 'notice13', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(14, 1, 'geniecar_image', 'notice14.png', 'notice14', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(15, 1, 'geniecar_image', 'notice15.png', 'notice15', '.png', 600000, 'ADMIN', '2023/12/25');

-- 이벤트 삽입
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '지니카에서 렌트 하고 해외 여행 가자!', '이벤트 내용 입니다.0', 0, 'EVENT', 'N', NULL, 16, '2023/12/25', '2024/01/31', 'ADMIN', '2023-12-25', 'ADMIN', '2023/12/25');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '지니카 이용객 전용 eSIM 최저가 이벤트', '이벤트 내용 입니다.1', 0, 'EVENT', 'N', NULL, 17, '2024/01/01', '2024/12/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '대한민국 No.1 지니카와 골프코스를!', '이벤트 내용 입니다.2', 0, 'EVENT', 'N', NULL, 18, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '지니카에서 따뜻한 커피와 함께 포근한 여행 되세요!', '이벤트 내용 입니다.3', 0, 'EVENT', 'N', NULL, 19, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '공항철도 이용한다면 지니카 회원전용 특별할인!', '이벤트 내용 입니다.4', 0, 'EVENT', 'N', NULL, 20, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '제주 자연을 품은 프라이빗한 공간에서 즐기는 펫캉스!', '이벤트 내용 입니다.5', 0, 'EVENT', 'N', NULL, 21, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '지니카 회원전용 아이스크림 홈런 무료체험 이벤트', '이벤트 내용 입니다.6', 0, 'EVENT', 'N', NULL, 22, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');

-- 이벤트 이미지 삽입 (이벤트당 이미지 2개)
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(16, 1, 'geniecar_image', 'evt0.png', 'evt0', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(16, 2, 'geniecar_image', 'evtd0.png', 'evtd0', '.png', 600000, 'ADMIN', '2023/12/25');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(17, 1, 'geniecar_image', 'evt1.png', 'evt1', '.png', 600000, 'ADMIN', '2024/01/01');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(17, 2, 'geniecar_image', 'evtd1.png', 'evtd1', '.png', 600000, 'ADMIN', '2024/01/01');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(18, 1, 'geniecar_image', 'evt2.png', 'evt2', '.png', 600000, 'ADMIN', '2024/01/01');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(18, 2, 'geniecar_image', 'evtd2.png', 'evtd2', '.png', 600000, 'ADMIN', '2024/01/01');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(19, 1, 'geniecar_image', 'evt3.png', 'evt3', '.png', 600000, 'ADMIN', '2024/01/01');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(19, 2, 'geniecar_image', 'evtd3.png', 'evtd3', '.png', 600000, 'ADMIN', '2024/01/01');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(20, 1, 'geniecar_image', 'evt4.png', 'evt4', '.png', 600000, 'ADMIN', '2024/01/01');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(20, 2, 'geniecar_image', 'evtd4.png', 'evtd4', '.png', 600000, 'ADMIN', '2024/01/01');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(21, 1, 'geniecar_image', 'evt5.png', 'evt5', '.png', 600000, 'ADMIN', '2024/01/01');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(21, 2, 'geniecar_image', 'evtd5.png', 'evtd5', '.png', 600000, 'ADMIN', '2024/01/01');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(22, 1, 'geniecar_image', 'evt6.png', 'evt6', '.png', 600000, 'ADMIN', '2024/01/01');
INSERT INTO IMAGE_FILE(FILE_NO, SEQ, SAVE_PATH, SAVE_NAME, FILE_NAME, EXTENSION, FILE_SIZE, REG_ID, REG_DATE) VALUES(22, 2, 'geniecar_image', 'evtd6.png', 'evtd6', '.png', 600000, 'ADMIN', '2024/01/01');

-- FAQ 삽입
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '본인확인은 왜 해야하나요?', '지니카는 본인확인과 신용심사를 통해 고객님에게 맞는 정확한 견적과 렌탈료를 제공합니다.<br>타사와 달리 첫 화면에 렌탈료가 노출되지 않는 건 고객님께 정확한 렌탈료를 빠르게 제공하기 위한 목적입니다.<br>또한 금융사와 달리 신용조회를 반복하여도 신용등급에는 영향을 미치지 않으니 걱정하지 마세요.', 0, 'FAQ', 'N', NULL, 23, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '지니카 상담센터 운영시간은 어떻게 되나요?', '지니카에서 이루어지는 견적/계약 진행, 다이렉트 상품 등의 문의사항을 해결해드려요.<br>상담 시간 외에는 상담예약을 남겨주시면 예약 시간에 전문 상담원이 연락을 드려요.<br>※ 다이렉트 상담센터 1588-0531 운영시간 : 평일 09:00~18:00 (토요일 및 공휴일 휴무)', 0, 'FAQ', 'N', NULL, 24, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '인수센터 방문 픽업에 대해 알고싶어요', 'Q: 지니카 고객 누구나 인수센터에서 방문 픽업이 가능한가요?<br>A: 지니카 "신차 계약 고객"이라면 누구나 인수센터 방문 픽업이 가능해요!<br>Q: 인수센터 방문 픽업의 장점이 무엇인가요?<br>A: 탁송보다 빠르게~꼼꼼한 검수는 기본, 주말(토요일)에도 이제 기다리지 말고 다이렉트하게 픽업하세요!<br>Q: 방문 고객 혜택이 별도로 있나요?<br>A: 내차를 직접 개봉하는 듯한 지니카만의 "언박싱 이벤트"는 물론 내연기관 고객님에게는 모바일주유권과 전기차 고객님에게는 완충서비스를 제공해드리고 있어요!<br>Q: 인수센터는 어디에 있나요?<br>A: 인천 연수구 테크노파크로 164 (송도센트럴파크) 지하3층에 위치하고 있으며 대중교통 이용시 담당 카매니저가 인근 지하철역에서 픽업을 도와드리고 있어요!<br>Q: 방문 픽업 방법을 알려주세요.<br>A: 계약 완료하고 배송지를 입력하신 후 직접 픽업하러가기를 선택해주세요. 선택 후 변경도 가능하니 담당 카매니저에게 문의주시면 변경을 도와드려요!', 0, 'FAQ', 'N', NULL, 25, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '여행이나 레저 목적으로 견인장치를 장착하고 싶은데 가능한가요?', '견인장치 장착이 가능하며, 희망할 경우 담당 카매니저에게 문의해주시면 자세하게 안내해 드려요.<br>단, 아래 내용을 꼭 확인해주세요!<br>- 신청 방법<br>1. 신청시 필요한 서류를 미리 준비하여 담당 카매니저에게 문의해주세요.<br>2. 보증금 납부절차를 안내받고 총 장착 금액의 150%를 납부해주세요.<br>3. 이후 절차는 카매니저가 자세히 안내해드릴 예정이에요<br>※ 준비서류 : 튜닝 승인 신청서, 구조변경 견적서<br>※ 차량 반납시 반드시 원상복구 하여 반납하여야 하며, 이를 어길시 보증금 반환에 제한이 있습니다.<br>- 특약보험<br>가입 견인장치 특약보험에 가입하여야 차량과 피견인차량이 견인장치로 연결된 상태로 운행 중 피견인차량으로 인해 발생한 사고에 한하여 보험처리를 받을 수 있어요.<br>특약보험 가입은 필수는 아니지만, 가입을 희망한다면 담당 카매니저에게 말씀해주세요. ※ 피견인차(트레일러, 카라반 등) 자차보험은 필요시 별도로 가입하여야 합니다.', 0, 'FAQ', 'N', NULL, 26, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '몇 일만 운전자를 추가할 수 있나요?', '단기운전자는 지니카 고객센터로 전화주시면 추가할 수 있어요.<br>※ 지니카 고객센터 : 1588-0531 (평일 09:00~18:00)<br>※ 법인(개인)사업자 중 임직원 특약에 가입하신 고객님은 단기운전자 등록이 불가합니다.', 0, 'FAQ', 'N', NULL, 27, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '비밀번호를 잃어버렸어요.', '기존에 가입하신 휴대폰 번호로 비밀번호를 변경할 수 있어요.', 0, 'FAQ', 'N', NULL, 28, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '회원가입은 어떻게 하나요?', '휴대폰 인증 또는 카카오톡 계정을 통해 간편 회원가입 할 수 있어요.<br>(ID : 휴대폰번호) 또한 회원가입 시 로그인을 통해 14일간 간편인증을 PASS하여 보다 편리하게 견적과 계약을 진행할 수 있어요.', 0, 'FAQ', 'N', NULL, 29, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '지니카 고객센터 운영시간은 어떻게 되나요?', '사고/수리 접수, 단기/월간 대여 등의 문의사항을 해결해 드려요.<br>(사고접수 24시간 운영)<br>※ 지니카 고객센터 1588-0531 운영시간 : 평일 09:00~18:00 (토요일 및 공휴일 휴무)', 0, 'FAQ', 'N', NULL, 30, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '사고가 나면 수리는 어떻게 진행되나요?', '사고 시 수리 진행 절차를 알려드릴게요.<br>1. 고객센터(1588-0531) 사고접수<br>2. 담당자 배정<br>3. 공장 입고<br>4. 견적 및 사고 부위 확인<br>5. 수리 승인<br>6. 수리 완료<br>7. 회수 요청<br>8. 면책금 납부 확인(국산차 30만원 / 수입차 50만원)<br>9. 고객에게 배송<br>※ 면책금 미납부시 출고 진행이 어렵습니다.', 0, 'FAQ', 'N', NULL, 31, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '긴급출동 서비스는 무엇이고, 신청은 어떻게 하나요?', '지니카 고객센터에서는 24시간 긴급출동 서비스를 운영하고 있어요.<br>1588-0531로 전화 후 1번 > 4번 긴급출동 접수를 선택해주세요.<br>긴급출동 서비스 제공 내역을 알려드릴게요.<br>· 비상급유서비스 (운행중 기름이 떨어졌을 때 3리터까지 급유)<br>· 잠금장치 해제 서비스 (열쇠를 차 안에 두고 잠궜을 때)<br>· 배터리 충전 서비스 (배터리 방전으로 운행 불가시)<br>· 타이어 펑크 수리 서비스 (타이어 펑크로 운행 불가시)<br>· 긴급 견인 서비스 (고장 및 사고로 운행 불가시) ', 0, 'FAQ', 'N', NULL, 32, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '전기차를 처음 타보는데, 운행방법은 어디서 알 수 있나요?', '차량 배송시 고객님의 담당 카매니저가 직접 방문하여 운행방법에 대해 안내드릴 예정이에요.', 0, 'FAQ', 'N', NULL, 33, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '전기차 충전소는 어떻게 찾나요?', '충전기 위치는 www.ev.or.kr에서 확인할 수 있으며, 모바일의 경우는 EV링크 APP 설치를 추천드려요.<br>EV링크는 지니카가 출시한 전기차 전용 APP으로, 편리한 충전서비스를 이용하고 싶으시다면 설치하여 사용해주세요!', 0, 'FAQ', 'N', NULL, 34, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '전기차 충전카드 신청방법이 궁금해요.', '1. 전기차 충전사업자 별 홈페이지에 접속하여 충전카드를 신청해주세요. 충전카드 수령 후 꼭 결제 가능한 신용카드를 등록해주셔야 충전이 가능해요.<br>2. 지니카에서 제공하는 EV링크 APP을 설치하시고 회원가입 하시면 충전카드를 발급해 드려요. 회원 가입 시 꼭 결제가능한 신용카드를 등록해 주셔야 충전이 가능해요.', 0, 'FAQ', 'N', NULL, 35, '2024/01/01', '2024/05/31', 'ADMIN', '2024-01-01', 'ADMIN', '2024/01/01');

-- 1:1 문의
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '차 안에 핸드폰을 떨어 뜨린것 같아요ㅠㅠ!', '어떻게 찾아 볼 수 있을까요?', 0, 'QNA', 'N', NULL, 36, '2024/01/01', '2024/05/31', 'hong', '2024-01-15', 'hong', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '애견 동반 가능한가요?', '울 강쥐랑 같이 여행 가려구요~!', 0, 'QNA', 'N', NULL, 37, '2024/01/01', '2024/05/31', 'hong', '2024-01-16', 'hong', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '차에서 담배냄새가 심하게 나요!!', '다른 차로 바꾸고 싶어요', 0, 'QNA', 'N', NULL, 38, '2024/01/01', '2024/05/31', 'sdy', '2024-01-17', 'sdy', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '운전자는 몇 명까지 운전 가능한가요?', '친구랑 돌아가면서 운전 하려고 해요!', 0, 'QNA', 'N', NULL, 39, '2024/01/01', '2024/05/31', 'kdh', '2024-01-18', 'kdh', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '외부에서 인수/반납 되나요?', '차를 지점 까지 가져가기 힘들꺼 같아요', 0, 'QNA', 'N', NULL, 40, '2024/01/01', '2024/05/31', 'msy', '2024-01-19', 'msy', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '영업시간은 몇 시 까지인가요?', '오늘 저녁 늦게 도착 할 것 같은데..시간이 애매해요', 0, 'QNA', 'N', NULL, 41, '2024/01/01', '2024/05/31', 'pnr', '2024-01-20', 'pnr', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '반납예정 시간보다 늦게 반납하면 어떻게 되나요?', '추가요금이 어떻게 발생하는지 궁금해요', 0, 'QNA', 'N', NULL, 42, '2024/01/01', '2024/05/31', 'ljy', '2024-01-21', 'ljy', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '차를 어디서 인수하게 되나요?', '지점으로 찾아가기 힘들꺼 같아요~', 0, 'QNA', 'N', NULL, 43, '2024/01/01', '2024/05/31', 'kty', '2024-01-15', 'kty', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '새벽에도 차를 받을 수 있나요?', '새벽5시 쯤 도착 예정이라서요!', 0, 'QNA', 'N', NULL, 44, '2024/01/01', '2024/05/31', 'jhh', '2024-01-14', 'jhh', '2024/01/01');
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '차를 일찍 반납하고 싶어요!', '예약한 기간 보다 일찍 반납 하려고 하는데 환불은 되나요?', 0, 'QNA', 'N', NULL, 45, '2024/01/01', '2024/05/31', 'key', '2024-01-17', 'key', '2024/01/01');

-- 이벤트 당첨자 발표
INSERT INTO BOARD(NO, PARENT_NO, TITLE, CONTENT, HIT, TYPE_CODE, NOTICE_YN, HASH_TAG, FILE_NO, START_DATE, END_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE) VALUES(SEQ_BOARD_NO.NEXTVAL, 0, '지니카에서 렌트 하고 해외 여행 가자! (당첨자 발표!)', '지니카에서 렌트하고 해외 여행 가자!<br>당첨자 발표 입니다!<br><br>-------------------당 첨 명 단-------------------<br><br>홍*혜 님<br>홍*영 님<br>이*진 님<br><br>당첨을 진심으로 축하드립니다.^0^)/<br><br>이벤트 관련 안내는 개별 연락 드리도록 하겠습니다!!<br>감사합니다!', 0, 'EVENTWINNER', 'N', NULL, 45, '2024/01/01', '2024/05/31', 'ADMIN', '2024-02-05', 'ADMIN', '2024/01/01');

COMMIT;