INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '홍성혜', '010-0000-0000', 'hsh@geniecar.com', '캐스퍼로 출퇴근 렌터카 진행하려고 합니다.'|| chr(10) || chr(13) || '확인히시면 연락주세요', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '홍경영', '010-0000-0000', 'hky@geniecar.com', '아반떼로 3개월 정도 렌트하고 싶어요.'|| chr(10) || chr(13) || '비용 확인 하셔서 연락부탁드립니다.', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '이재진', '010-0000-0000', 'ljj@geniecar.com', '쏘나타로 한달 예약하려고 하는데 추가 할인이 되나요?'|| chr(10) || chr(13) || '할인이 얼마나 되는지 확인하고 싶습니다.', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '김유정', '010-0000-0000', 'kyj@geniecar.com', '모닝으로 6개월 렌터카 진행하려고 합니다.'|| chr(10) || chr(13) || '비용이 얼마 정도 들까요?', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '홍나은', '010-0000-0000', 'hne@geniecar.com', '레이로 1년 렌터카 진행하려고 하는데 얼마정도 비용이 들까요?.'|| chr(10) || chr(13) || '연식은 좋은 넘으로 부탁 드립니다.', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '전지원', '010-0000-0000', 'jjw@geniecar.com', '렉스턴으로 단기 예약 가능한가요?'|| chr(10) || chr(13) || '대전 지점에 확인 부탁 드립니다.', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '한아름', '010-0000-0000', 'har@geniecar.com', '싼타페로 출퇴근 렌터카는 얼마정도 비용이 나올까요?'|| chr(10) || chr(13) || '구형으로 주셔도 되용 젤루 싼걸루 주세요!!', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '윤소혜', '010-0000-0000', 'ysh@geniecar.com', 'k5로 두 달 렌터카 진행하고 싶은데 어떻게 요청하면 되나요?'|| chr(10) || chr(13) || '최신모델로 확인 해주세요!', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '한주아', '010-0000-0000', 'hja@geniecar.com', '스포티지로 한달 예약하려고 하는데 추가 할인이 되나요?'|| chr(10) || chr(13) || '할인율이 얼마나 되고 총 비용은 얼마정도 드는지 알고싶어요', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '김예지', '010-0000-0000', 'kyj@geniecar.com', 'G90으로 제주도 단기 렌트하고 싶어요'|| chr(10) || chr(13) || '리무진은 제외하구 확인 부탁드려용', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '이규민', '010-0000-0000', 'lkm@geniecar.com', '카니발로 일주일 렌트 시 비용을 알고 싶어요'|| chr(10) || chr(13) || '여행갈때 쓸건테 텐트 사용 가능 차량 있을까요>', 'SEO001', SYSDATE, 'N');
INSERT INTO CONSULT (NO, NAME, TEL, EMAIL, PURPOSE, WISH_REGION, REG_DATE, STATUS_YN) VALUES (SEQ_CONSULT_NO.NEXTVAL, '김나래', '010-0000-0000', 'knr@geniecar.com', '모하비로 하루 예약하려고 하는데 추가 할인이 있나요?'|| chr(10) || chr(13) || '하루라서 할인이 될진 모르겠지만 조금 구식이라도 저렴한걸로 알아보교 연락 주세요~', 'SEO001', SYSDATE, 'N');

COMMIT;