SELECT * FROM COMMON_CODE;
SELECT * FROM MEMBER;
SELECT * FROM RENTAL_CAR;
SELECT * FROM RENTAL_CAR_BRANCH;
SELECT * FROM RENTAL_CAR_BRANCHES_CAR;
SELECT * FROM POINT;
SELECT * FROM CONSULT;
SELECT * FROM BOARD;
SELECT * FROM IMAGE_FILE;
SELECT * FROM RENTAL_CAR_RESERVATION;
SELECT * FROM NEW_CAR;
SELECT * FROM LICENSE;
SELECT * FROM POINT;
SELECT * FROM PAYMENT;
commit;

INSERT INTO POINT VALUES (998, 20000, '+', '회원가입 포인트 적립', SYSDATE-2, 20000, 0, 'sdy');

