/*
공통코드 (3자리) 이름 조회하는 함수
*/
CREATE OR REPLACE FUNCTION FN_COMM_NM(VS_CODE VARCHAR2)
    RETURN VARCHAR2
IS
    VS_CODE_NAME VARCHAR2(50);
BEGIN

    SELECT CODE_NAME INTO VS_CODE_NAME FROM COMMON_CODE WHERE CODE = (SUBSTR(VS_CODE, 4, 3));
    RETURN VS_CODE_NAME;

END;
/

/*
공통코드 풀네임(6자리)으로 이름 조회하는 함수
*/
CREATE OR REPLACE FUNCTION FN_COMM_NAME(VS_CODE VARCHAR2)
    RETURN VARCHAR2
    IS
    VS_CODE_NAME VARCHAR2(50);
BEGIN

SELECT CODE_NAME INTO VS_CODE_NAME FROM COMMON_CODE WHERE CODE = (SUBSTR(VS_CODE, 4, 3)) AND GROUP_CODE = (SUBSTR(VS_CODE, 1, 3));

RETURN VS_CODE_NAME;
END;
/


/*
RENTAL_CAR_RESERVATION 예약번호 만들어주는 함수
*/
CREATE OR REPLACE FUNCTION FN_RES_NO
    RETURN VARCHAR2
    IS
    VS_RES_NO VARCHAR2(20);
BEGIN
    SELECT 'RES' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || LPAD(SEQ_RESERVATION_NO.NEXTVAL, 8, '0')
    INTO VS_RES_NO
    FROM DUAL;
    RETURN VS_RES_NO;
END;
/