INSERT INTO MEMBER VALUES ( 'hong', '1212', '홍성혜', 'F', '1989-08-03', '010-1111-1111', '대전광역시 중구', '수침로', '11111', SYSDATE, SYSDATE, 'N', 'SEO001', 'B');


-- 면허 테이블 회원 아이디 + 회원 테이블의 아이디
ALTER TABLE LICENSE
    ADD CONSTRAINT LICENSE_MEMBER_ID_FK
        FOREIGN KEY (MEMBER_ID)
            REFERENCES MEMBER (ID);


ALTER TABLE RENTAL_CAR_BRANCH -- 기준테이블
    ADD CONSTRAINT RENTAL_CAR_BRANCH_REG_ID_FK
        FOREIGN KEY (REG_ID)
            REFERENCES MEMBER (ID); -- 부모

ALTER TABLE RENTAL_CAR_BRANCH -- 기준테이블
    ADD CONSTRAINT RENTAL_CAR_BRANCH_MOD_ID_FK
        FOREIGN KEY (MOD_ID)
            REFERENCES MEMBER (ID); -- 부모

ALTER TABLE 테이블이름 -- 기준테이블
    ADD CONSTRAINT 제약조건이름
        FOREIGN KEY (필드이름)
            REFERENCES 테이블이름 (필드이름); -- 부모

ALTER TABLE 테이블이름 -- 기준테이블
    ADD CONSTRAINT 제약조건이름
        FOREIGN KEY (필드이름)
            REFERENCES 테이블이름 (필드이름); -- 부모

ALTER TABLE 테이블이름 -- 기준테이블
    ADD CONSTRAINT 제약조건이름
        FOREIGN KEY (필드이름)
            REFERENCES 테이블이름 (필드이름); -- 부모







/*
UPDATE RENTAL_CAR_BRANCHES_CAR
SET RENTAL_ABLE_STATUS = 'Y', IMPORT_CAR_YN = 'Y', MOD_ID = #{memberId}, MOD_DATE = SYSDATE
WHERE CAR_IDENTIFICATION_NUMBER = #{carNumber} AND RENTAL_CAR_BRANCH_NO = #{branchCode}
*/
/*CAR_NAME, CAR_FUEL_CODE 두개 값이 일치하면 DEFAULT_COST의 값을 RENTAL_CAR_BRANCHES_CAR에 SET*/

SELECT * FROM RENTAL_CAR_BRANCHES_CAR WHERE DEFAULT_COST = (SELECT DEFAULT_COST FROM NEW_CAR WHERE CAR_NAME_CODE = 'HDI001' AND CAR_FUEL_CODE = 'FUEGAS') ;

