-- 파일 번호 (파일 시퀀스 FK)
ALTER TABLE BOARD
    ADD CONSTRAINT B_FILE_NO_FK
        FOREIGN KEY (FILE_NO)
            REFERENCES IMAGE_FILE (FILE_NO);
-- 기본 대여료 (NEW_CAR DEFAULT_COST FK)
ALTER TABLE RENTAL_CAR_BRANCHES_CAR
    ADD CONSTRAINT RCBC_DEFAULT_COST_FK
        FOREIGN KEY (DEFAULT_COST)
            REFERENCES NEW_CAR (DEFAULT_COST);
/*
UPDATE RENTAL_CAR_BRANCHES_CAR
SET RENTAL_ABLE_STATUS = 'Y', IMPORT_CAR_YN = 'Y', MOD_ID = #{memberId}, MOD_DATE = SYSDATE
WHERE CAR_IDENTIFICATION_NUMBER = #{carNumber} AND RENTAL_CAR_BRANCH_NO = #{branchCode}
*/
/*CAR_NAME, CAR_FUEL_CODE 두개 값이 일치하면 DEFAULT_COST의 값을 RENTAL_CAR_BRANCHES_CAR에 SET*/

SELECT * FROM RENTAL_CAR_BRANCHES_CAR WHERE DEFAULT_COST = (SELECT DEFAULT_COST FROM NEW_CAR WHERE CAR_NAME_CODE = 'HDI001' AND CAR_FUEL_CODE = 'FUEGAS') ;
