CREATE OR REPLACE VIEW RENTAL_CAR_VIEW
AS
SELECT RC.CAR_IDENTIFICATION_NUMBER
     ,NC.CAR_NAME --차명
     ,RC.CAR_NO
     ,NC.CAR_TYPE_CODE
     ,FN_COMM_NAME(NC.CAR_TYPE_CODE) AS CAR_TYPE --차종
     ,NC.CAR_FUEL_CODE
     ,FN_COMM_NAME(NC.CAR_FUEL_CODE) AS CAR_FUEL --연료
     ,NC.COMPANY
     ,FN_COMM_NAME(NC.COMPANY) AS COMPANY_NAME --제조사
     ,RC.DELIVERY_DATE
FROM NEW_CAR NC, RENTAL_CAR RC
WHERE NC.NO = RC.CAR_NO;