CREATE OR REPLACE VIEW RENTAL_CAR_VIEW
AS
SELECT RC.CAR_IDENTIFICATION_NUMBER
     ,NC.CAR_NAME --차명
     ,RC.CAR_NO
     ,NC.CAR_TYPE_CODE
     ,FN_COMM_NAME(NC.CAR_TYPE_CODE) AS CAR_TYPE --차종
     ,NC.CAR_FUEL_CODE
     ,FN_COMM_NAME(NC.CAR_FUEL_CODE) AS CAR_FUEL --연료
     ,NC.COMPANY
     ,FN_COMM_NAME(NC.COMPANY) AS COMPANY_NAME --제조사
     ,RC.DELIVERY_DATE
FROM NEW_CAR NC, RENTAL_CAR RC
WHERE NC.NO = RC.CAR_NO;

CREATE OR REPLACE VIEW RESERVATION_VIEW
AS
SELECT RCR.RESERVATION_NO
     , RENTAL_PLACE
     , FN_COMM_NAME(RENTAL_PLACE)         AS RENTAL_PLACE_NAME
     , RETURN_PLACE
     , FN_COMM_NAME(RETURN_PLACE)         AS RETURN_PLACE_NAME
     , RENTAL_DATE
     , RETURN_DATE
     , RCR.CAR_IDENTIFICATION_NUMBER
     , RENTAL_CAR_BRANCH_NO
     , FN_COMM_NAME(RENTAL_CAR_BRANCH_NO) AS RENTAL_CAR_BRANCH_NAME
     , RESERVATION_MEMBER_ID
     , M.NAME                             AS RESERVATION_MEMBER_NAME
     , HP                                 AS RESERVATION_MEMBER_HP
     , REGULAR_PRICE
     , SALE_RATE
     , FINAL_RESERVATION_PRICE
     , RCR.REG_ID
     , RCR.REG_DATE
     , RCR.MOD_ID
     , RCR.MOD_DATE
     , FN_COMM_NAME(CAR_FUEL_CODE)        AS FUEL_NAME
     , FN_COMM_NAME(CAR_TYPE_CODE)        AS TYPE_NAME
     , CAR_NAME
     , CANCEL_YN
FROM RENTAL_CAR_RESERVATION RCR,
     MEMBER M,
     RENTAL_CAR RC,
     NEW_CAR NC
WHERE RCR.RESERVATION_MEMBER_ID = M.ID
  AND RCR.CAR_IDENTIFICATION_NUMBER = RC.CAR_IDENTIFICATION_NUMBER
  AND RC.CAR_NO = NC.NO;