
spring:
  datasource:
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:XE
    username: GENIECAR
    password: 1212
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/**/*-mapper.xml

logging:
  config: classpath:logback-spring.xml